server:
  port: 8094
  servlet:
    context-path: /api
    application-display-name: ticketsystem
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  file:
    path: target/logs
com:
  blake:
    system:
      max-ticket-purchasable: 4